package br.com.fontana.loja.funcionario.entity;
// Generated Oct 31, 2014 10:30:39 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbCatgFunc generated by hbm2java
 */
@Entity
@Table(name = "TB_CATG_FUNC")
public class TbCatgFunc implements Serializable {

	private static final long serialVersionUID = -497317401799565509L;
	private short cdCatg;
	private TbTipoCargFunc tbTipoCargFunc;
	private String nmCatg;
	private char inUtizPlan;
	private Date dhInclRegt;
	private Date dhUltiAtlzRegt;
	private String dsCatgAbrv;
	private String tpPessCatg;
	private Set<TbFunc> tbFuncs = new HashSet<>(0);

	public TbCatgFunc() {
	}

	public TbCatgFunc(short cdCatg, String nmCatg, char inUtizPlan, Date dhInclRegt, Date dhUltiAtlzRegt) {
		this.cdCatg = cdCatg;
		this.nmCatg = nmCatg;
		this.inUtizPlan = inUtizPlan;
		this.dhInclRegt = dhInclRegt;
		this.dhUltiAtlzRegt = dhUltiAtlzRegt;
	}

	public TbCatgFunc(short cdCatg, TbTipoCargFunc tbTipoCargFunc, String nmCatg, char inUtizPlan, Date dhInclRegt, Date dhUltiAtlzRegt, String dsCatgAbrv, Set<TbFunc> tbFuncs) {
		this.cdCatg = cdCatg;
		this.tbTipoCargFunc = tbTipoCargFunc;
		this.nmCatg = nmCatg;
		this.inUtizPlan = inUtizPlan;
		this.dhInclRegt = dhInclRegt;
		this.dhUltiAtlzRegt = dhUltiAtlzRegt;
		this.dsCatgAbrv = dsCatgAbrv;
		this.tbFuncs = tbFuncs;
	}

	@Id
	@Column(name = "CD_CATG", unique = true, nullable = false, precision = 3, scale = 0)
	public short getCdCatg() {
		return this.cdCatg;
	}

	public void setCdCatg(short cdCatg) {
		this.cdCatg = cdCatg;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TP_CARG_FUNC")
	public TbTipoCargFunc getTbTipoCargFunc() {
		return this.tbTipoCargFunc;
	}

	public void setTbTipoCargFunc(TbTipoCargFunc tbTipoCargFunc) {
		this.tbTipoCargFunc = tbTipoCargFunc;
	}

	@Column(name = "NM_CATG", nullable = false, length = 50)
	public String getNmCatg() {
		return this.nmCatg;
	}

	public void setNmCatg(String nmCatg) {
		this.nmCatg = nmCatg;
	}

	@Column(name = "IN_UTIZ_PLAN", nullable = false, length = 1)
	public char getInUtizPlan() {
		return this.inUtizPlan;
	}

	public void setInUtizPlan(char inUtizPlan) {
		this.inUtizPlan = inUtizPlan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DH_INCL_REGT", nullable = false, length = 7)
	public Date getDhInclRegt() {
		return this.dhInclRegt;
	}

	public void setDhInclRegt(Date dhInclRegt) {
		this.dhInclRegt = dhInclRegt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DH_ULTI_ATLZ_REGT", nullable = false, length = 7)
	public Date getDhUltiAtlzRegt() {
		return this.dhUltiAtlzRegt;
	}

	public void setDhUltiAtlzRegt(Date dhUltiAtlzRegt) {
		this.dhUltiAtlzRegt = dhUltiAtlzRegt;
	}

	@Column(name = "DS_CATG_ABRV", length = 30)
	public String getDsCatgAbrv() {
		return this.dsCatgAbrv;
	}

	public void setDsCatgAbrv(String dsCatgAbrv) {
		this.dsCatgAbrv = dsCatgAbrv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbCatgFunc")
	public Set<TbFunc> getTbFuncs() {
		return this.tbFuncs;
	}

	public void setTbFuncs(Set<TbFunc> tbFuncs) {
		this.tbFuncs = tbFuncs;
	}
	@Column(name = "TP_PESS_CATG", length = 1)
	public String getTpPessCatg() {
		return tpPessCatg;
	}

	public void setTpPessCatg(String tpPessCatg) {
		this.tpPessCatg = tpPessCatg;
	}
}
 
