package br.com.fontana.loja.funcionario.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * TbTipoCargFunc generated by hbm2java
 */

@Entity
@Table(name = "TB_TIPO_CARG_FUNC", schema = "LOJA")
public class TbTipoCargFunc implements Serializable {

	private static final long serialVersionUID = -154213831665589327L;
	@Id
	@Column(name = "TP_CARG_FUNC", unique = true, nullable = false, length = 2)
	private String tpCargFunc;
	@Column(name = "DS_TIPO_CARG_FUNC", nullable = false, length = 40)
	private String dsTipoCargFunc;
	@Column(name = "DS_TIPO_CARG_ABRV", length = 30)
	private String dsTipoCargAbrv;


	public TbTipoCargFunc() {
	}

	public TbTipoCargFunc(String tpCargFunc, String dsTipoCargFunc) {
		this.tpCargFunc = tpCargFunc;
		this.dsTipoCargFunc = dsTipoCargFunc;
	}

	public TbTipoCargFunc(String tpCargFunc, String dsTipoCargFunc, String dsTipoCargAbrv) {
		this.tpCargFunc = tpCargFunc;
		this.dsTipoCargFunc = dsTipoCargFunc;
		this.dsTipoCargAbrv = dsTipoCargAbrv;
	}


	public String getTpCargFunc() {
		return this.tpCargFunc;
	}

	public void setTpCargFunc(String tpCargFunc) {
		this.tpCargFunc = tpCargFunc;
	}

	public String getDsTipoCargFunc() {
		return this.dsTipoCargFunc;
	}

	public void setDsTipoCargFunc(String dsTipoCargFunc) {
		this.dsTipoCargFunc = dsTipoCargFunc;
	}

	public String getDsTipoCargAbrv() {
		return this.dsTipoCargAbrv;
	}

	public void setDsTipoCargAbrv(String dsTipoCargAbrv) {
		this.dsTipoCargAbrv = dsTipoCargAbrv;
	}

}
 
